[package]
name = "secsnail"
version = "1.0.1"
edition = "2024"
authors = ["Luis AndrÃ©s Boden <luis.boden@gmail.com>", "Jan Spennemann"]
description = "Secure Snail Protocol ğŸŒ for file transfer, implemented in rust."
license = "MIT"
repository = "https://github.com/SilverfangONE/secsnail"

[dependencies]
crc = "3.4.0"
crc-catalog = "2.4.0"
rand = "0.9.2"
clap = { version = "4.5", features = ["derive"], optional = true }

[features]
bin-deps = ["dep:clap"]

[[bin]]
name = "server"
path = "src/bin/server.rs"
required-features = ["bin-deps"]

[[bin]]
name = "client"
path = "src/bin/client.rs"
required-features = ["bin-deps"]

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
strip = true
panic = "abort"
